// Export all services
export { userService } from './userService'
export { transactionService } from './transactionService'
export { documentService } from './documentService'
export { reminderService } from './reminderService'
export { taxCalculationService } from './taxCalculationService'
export { taxPaymentService } from './taxPaymentService'
export { reportService } from './reportService'
export type { ReportData, ReportPeriod, IncomeData, ExpenseData, TaxData } from './reportService'
export type { SavedReport, ReportType, ReportStatus } from '@/lib/types'
export { exchangeRateService } from './exchangeRateService'
export { advancedAnalyticsService } from './advancedAnalyticsService'
export type { MonthlyAggregation, YearlyAggregation, ComparativeMetrics, TrendAnalysis, Forecast } from './advancedAnalyticsService'
export { conversationService } from './conversationService'
export { ocrService } from './ocrService'
export { invoiceService } from './invoiceService'
export { capitalAssetService } from './capitalAssetService'
export { brandDealService } from './brandDealService'
export { businessEntityService } from './businessEntityService'
export type { ExchangeRate } from './exchangeRateService'
export type { Conversation, ConversationMessage } from './conversationService'
export type { ReceiptData } from './ocrService'
export type { CapitalAsset } from './capitalAssetService'

// Export base service for extending
export { BaseService } from './base'
